let frontArray = [
  {
    name: "HTML",
    course: [
      "Introduction to HTML",
      "Browsers and HTML",
      "Editor’s Offline and Online",
      "Tags, Attribute and Elements",
      "Doctype Element",
      "Comments",
      "Headings, Paragraphs, and Formatting Text",
      "Lists and Links",
      "Images and Tables",
    ],
  },

  {
    name: "CSS",
    course: [
      "Introduction CSS",
      "Applying CSS to HTML",
      "Selectors, Properties and Values",
      "CSS Colors and Backgrounds",
      "CSS Box Model",
      "CSS Margins, Padding, and Borders",
      "CSS Text and Font Properties",
      "CSS General Topics",
    ],
  },

  {
    name: "Javascript",
    course: [
      "Introduction to JavaScript",
      "Applying JavaScript (internal and external)",
      "Understanding JS Syntax",
      "Introduction to Document and Window Object",
      "Variables and Operators",
      "Data Types and Num Type Conversion",
      "Math and String Manipulation",
      "Objects and Arrays",
      "Date and Time",
      "Conditional Statements",
      "Switch Case ",
      "Looping in JS",
      "Functions",
    ],
  },
  {
    name: "ReactJS",
    course: [
      "Introduction",
      "Templating using JSX",
      "Components, State and Props",
      "Lifecycle of Components",
      "Rendering List and Portals",
      "Error Handling",
      "Routers",
      "Redux and Redux Saga",
      "Immutable.js",
      "Service Side Rendering",
      "Unit Testing",
      "Webpack",
    ],
  },
];

let backArray = [
  {
    name: "NodeJS",
    course: [
      "Node js Overview",
      "Node js - Basics and Setup",
      "Node js Console",
      "Node js Command Utilities",
      "Node js Modules",
      "Node js Concepts",
      "Node js Events",
      "Node js with Express js",
      "Node js Database Access",
    ],
  },
  {
    name: "MongoDB",
    course: [
      "SQL and NoSql Concepts",
      "Create and Manage MongoDB",
      "Migration of Data into MongoDB",
      "MongoDB with PHP",
      "MongoDB with NodeJS",
      "Services Offered by MongoDB",
    ],
  },
  {
    name: "PHP and SQL",
    course: [
      "Introduction to PHP",
      "Decisions and loop",
      "Function",
      "Array",
      "Handling Html Form with Php",
      "Working with file and Directories",
      ". Session and Cookie",
      "Database Connectivity with MySql",
      "Exception Handling",
      "Manage Databases",
      "MySQL Table Types",
      "MySQL Data Types",
      "MySQL CREATE TABLE",
      "MySQL Primary Key",
      "MySQL Foreign Key",
      "MySQL Sequence",
      "MySQL INT Data Type",
      "MySQL DECIMAL Data Type",
      " MySQL DATE Data Type",
      " MySQL TIME Data Type",
      "MySQL DATETIME Data Type",
      "MySQL ALTER TABLE",
      "MySQL RENAME TABLE",
      "MySQL ADD COLUMN",
      "MySQL DROP TABLE",
      "MySQL Temporary Table",
    ],
  },
];

export { frontArray, backArray };
