let javaScriptArray = [
  "JavaScript Introduction",
  "JavaScript Statements",
  "JavaScript Syntax",
  "JavaScript Comments",
  "JavaScript Identifiers",
  "JavaScript Operators",
  "JavaScript Data Types",
  "JavaScript Functions",
  "JavaScript Objects",
  "JavaScript Events",
  "JavaScript Strings",
  "JavaScript String Methods",
  "JavaScript Numbers",
  "JavaScript Number Methods",
  "JavaScript Arrays",
  "JavaScript Array Methods",
  "JavaScript Sorting Arrays",
  "JavaScript Array Iteration Methods",
  "JavaScript Date Objects",
  "JavaScript Date Formats",
  "JavaScript Get Date Methods",
  "JavaScript Set Date Methods",
  "JavaScript Math Object",
  "JavaScript Random",
  "JavaScript Booleans",
  "JavaScript Comparison and Logical Operators",
  "JavaScript if else and else if",
  "JavaScript Switch Statement",
  "JavaScript For Loop",
  "JavaScript While Loop",
  "JavaScript Do/While Loop",
  "JavaScript Break and Continue",
  "JavaScript Type Conversion",
  "JavaScript Regular Expressions",
  "JavaScript Errors - Throw and Try to Catch",
  "JavaScript Scope",
  "JavaScript Hoisting",
  "JavaScript Use Strict",
  "JavaScript this Keyword",
  "JavaScript Let",
  "JavaScript Const",
  "JavaScript Debugging",
  "JavaScript Style Guide and Coding Conventions",
  "JavaScript Common Mistakes",
  "JavaScript Performance",
  "JavaScript Reserved Words",
  "JavaScript Versions",
  "ECMAScript 5 - JavaScript 5",
  "ECMAScript 6 - ECMAScript 2015",
  "JavaScript JSON",
  "JavaScript Forms",
  "JavaScript Validation API",
  "JavaScript objects",
  "JavaScript Object Properties",
  "JavaScript Object Methods",
  "JavaScript Object Accessors",
  "JavaScript Object Constructors",
  "JavaScript Object Prototypes",
  "JavaScript ES5 Object Methods",
  "JS Functions",
  "JavaScript Function Definitions",
  "JavaScript Function Parameters",
  "JavaScript Function Invocation",
  "JavaScript Function Call",
  "JavaScript Function Apply",
  "javaScript Closures",
  "JS HTML DOM",
  "JavaScript HTML DOM",
  "JavaScript - HTML DOM Methods",
  "JavaScript HTML DOM Document",
  "JavaScript HTML DOM Elements",
  "JavaScript HTML DOM - Changing HTML",
  "JavaScript HTML DOM - Changing CSS",
  "JavaScript HTML DOM Animation",
  "JavaScript HTML DOM Events",
  "JavaScript HTML DOM EventListener",
  "JavaScript HTML DOM Navigation",
  "JavaScript HTML DOM Elements (Nodes)",
  "JavaScript HTML DOM Collections",
  "JavaScript HTML DOM Node Lists",
  "JS Browser BOM",
  "JavaScript Window - The Browser Object Model",
  "JavaScript Window Screen",
  "JavaScript Window Location",
  "JavaScript Window History",
  "JavaScript Window Navigator",
  "JavaScript Popup Boxes",
  "JavaScript Timing Events",
  "JavaScript Cookies",
];

console.log(javaScriptArray);

var javaScriptCourse = document.getElementById("javaScriptCourse");
console.log(javaScriptCourse);

for (var i in javaScriptArray) {
  javaScriptCourse.innerHTML += `
        <li>
            <a>${javaScriptArray[i]}</a>
        </li>
    `;
}
